RentalManagement/Models/MaintenanceRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace RentalManagement.Models
{
    public class MaintenanceRequest
    {
        [ScaffoldColumn(false)]
        public Guid ID { get; set; }

        public Tenant Tenant { get; set; }

        public Asset Asset { get; set; }

        [Required(ErrorMessage = "A Created Date is Required!")]
        [DisplayName("Created Date")]
        public DateTime CreatedDate { get; set; }

        [DisplayName("Completed Date")]
        public DateTime? CompletedDate { get; set; }

        [Required(ErrorMessage = "A Subject is Required!")]
        [StringLength(100)]
        public string Subject { get; set; }

        [DisplayName("Request Details")]
        [StringLength(1000)]
        public string RequestDetail { get; set; }

        [DisplayName("Status Details")]
        [StringLength(1000)]
        public string StatusDetail { get; set; }

        [DisplayName("Fix Details")]
        [StringLength(1000)]
        public string FixDetail { get; set; }

        [DisplayName("Hours")]
        [Range(0, 100)]
        public int HoursSpent { get; set; }

        public virtual ICollection<Appliance> Appliances { get; set; }
    }
}

RentalManagement/Controllers/MaintenanceRequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RentalManagement.Models;
using RentalManagement.CustomFilters;
using Microsoft.AspNet.Identity;

namespace RentalManagement.Controllers
{
    [AuthLog(Roles = "Admin, Manager, Staff, Tenant")]
    public class MaintenanceRequestsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MaintenanceRequests
        public ActionResult Index()
        {
            var assetGroupQuery = db.MaintenanceRequest.Include("Asset").GroupBy(a => a.Asset);
            Dictionary<string, string> numRequestPerAsset = new Dictionary<string, string>();
            foreach (var line in assetGroupQuery
                        .Include("Asset")
                        .Select(group => new {
                            group.Key.Name,
                            Count = group.Count().ToString()
                        })
                        .OrderByDescending(x => x.Name))
            {
                numRequestPerAsset.Add(line.Name, line.Count);
                Console.WriteLine("Asset name: {0}, requests: {1}", line.Name, line.Count);
            }
            ViewBag.NumRequestPerAsset = numRequestPerAsset;
            return View(db.MaintenanceRequest.OrderByDescending(a => a.CreatedDate).ToList());
        }

        // GET: MaintenanceRequests/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaintenanceRequest maintenanceRequest = db.MaintenanceRequest.Find(id);
            if (maintenanceRequest == null)
            {
                return HttpNotFound();
            }
            return View(maintenanceRequest);
        }

        // GET: MaintenanceRequests/Create
        public ActionResult Create()
        {
            var assets = db.Assets.ToList();
            List<SelectListItem> list = assets.ConvertAll(a =>
                                        {
                                            return new SelectListItem()
                                            {
                                                Text = a.Name,
                                                Value = a.ID.ToString(),
                                                Selected = false
                                            };
                                        });
            ViewBag.AssetList = new SelectList(list, "Value", "Text");
            ViewBag.ApplianceList = null;

            if (User.IsInRole("Tenant"))
            {
                // Find the asset for the tenant   
                var currentUserId = User.Identity.GetUserId();
                var currentUser = db.Users.Include("Tenant").SingleOrDefault(s => s.Id == currentUserId);
                Tenant tenant = currentUser.Tenant;

                Asset asset = db.Occupancies
                            .Include("AssetID")
                            .Include("ClientID")
                            .Where(s => s.ClientID.ID == tenant.ID)
                            .First().AssetID;
                
                // Get list of appliances for the asset
                var appliancesInAsset = db.Assets.Include("Appliances").Where(a => a.ID == asset.ID).FirstOrDefault().Appliances;
                // 
                List<SelectListItem> aList = new List<SelectListItem>();
                foreach (Appliance a in appliancesInAsset)
                {
                    aList.Add(new SelectListItem()
                    {
                        Text = a.Name,
                        Value = a.ID.ToString(),
                        Selected = false
                    });
                }
                ViewBag.ApplianceList = new MultiSelectList(aList, "Value", "Text");
            }
            return View();
        }

        // POST: MaintenanceRequests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthLog(Roles = "Admin, Manager, Staff, Tenant")]
        public ActionResult Create([Bind(Include = "Asset,Subject,RequestDetail")] MaintenanceRequest maintenanceRequest)
        {
            if (ModelState.IsValid)
            {
                // Tenant request creation
                if (User.IsInRole("Tenant"))
                {
                    maintenanceRequest.ID = Guid.NewGuid();
                    maintenanceRequest.CreatedDate = System.DateTime.Now;
                    maintenanceRequest.CompletedDate = null;

                    // Bind Asset and Tenant data from Occupancy for the currently logged in tenant user    
                    var currentUserId = User.Identity.GetUserId();
                    var currentUser = db.Users.Include("Tenant").SingleOrDefault(s => s.Id == currentUserId);
                    Tenant tenant = currentUser.Tenant;

                    maintenanceRequest.Tenant = tenant;
                        
                    Asset asset = db.Occupancies
                                .Include("AssetID")
                                .Include("ClientID")
                                .Where(s => s.ClientID.ID == tenant.ID)
                                .First().AssetID;
                    maintenanceRequest.Asset = asset;
                    db.MaintenanceRequest.Add(maintenanceRequest);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                // Admin, manager, staff request creation
                if (User.IsInRole("Admin") ||
                    User.IsInRole("Manager") ||
                    User.IsInRole("Staff"))
                {
                    maintenanceRequest.ID = Guid.NewGuid();
                    maintenanceRequest.CreatedDate = System.DateTime.Now;
                    maintenanceRequest.CompletedDate = null;

                    Asset selectedAsset = db.Assets.Find(Guid.Parse(Request["selectAsset"]));
                    maintenanceRequest.Asset = selectedAsset;
                    
                    // Look in Occupancies to check if a Tenant exists for the selected Asset
                    if (selectedAsset != null)
                    {
                        maintenanceRequest.Tenant = db.Occupancies
                                .Include("AssetID")
                                .Include("ClientID")
                                .Where(s => s.AssetID.ID == selectedAsset.ID)
                                .FirstOrDefault()?.ClientID;
                    }

                    db.MaintenanceRequest.Add(maintenanceRequest);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(maintenanceRequest);
        }

        // GET: MaintenanceRequests/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaintenanceRequest maintenanceRequest = db.MaintenanceRequest.Find(id);
            if (maintenanceRequest == null)
            {
                return HttpNotFound();
            }
            return View(maintenanceRequest);
        }

        // POST: MaintenanceRequests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CreatedDate,CompletedDate,Subject,RequestDetail,StatusDetail,FixDetail,HoursSpent")] MaintenanceRequest maintenanceRequest, string saveBtn, string closeBtn)
        {
            if (ModelState.IsValid && saveBtn != null)
            {
                db.Entry(maintenanceRequest).State = EntityState.Modified;
                db.SaveChanges();
                TempData["SavedChangesMessage"] = "All Changes Have Been Saved!";
                return RedirectToAction("Edit");
            }

            if(ModelState.IsValid && closeBtn != null)
            {
                //alert user to enter completion date and display error msg
                do
                {
                    TempData["CloseRequestMsgAlert"] = "Please Enter a Completion Date to Close Request";

                } while (ViewData.ModelState["CompletedDate"] == null);
                return RedirectToAction("Edit");
            }
            // if completedDate is filled, move request to 'closed' table
            if (ViewData.ModelState["CompletedDate"] != null && ModelState.IsValid && closeBtn != null)
            {
                db.Entry(maintenanceRequest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(maintenanceRequest);
        }

        // GET: MaintenanceRequests/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaintenanceRequest maintenanceRequest = db.MaintenanceRequest.Find(id);
            if (maintenanceRequest == null)
            {
                return HttpNotFound();
            }
            return View(maintenanceRequest);
        }

        // POST: MaintenanceRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {

RentalManagement/Views/MaintenanceRequests/Create.cshtml
@model RentalManagement.Models.MaintenanceRequest

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MaintenanceRequest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        @if (ViewContext.HttpContext.User.IsInRole("Admin")
            || ViewContext.HttpContext.User.IsInRole("Manager")
            || ViewContext.HttpContext.User.IsInRole("Staff"))
        {
        <div class="form-group">
            @Html.LabelFor(model => model.Asset, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("selectAsset", (SelectList)ViewBag.AssetList, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
            <br />
        }

        <div class="form-group">
            @Html.LabelFor(model => model.RequestDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.RequestDetail, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.TextAreaFor(model => model.RequestDetail, new { htmlAttributes = new { @class = "form-control" }, cols = 40, rows = 10 })
                @Html.ValidationMessageFor(model => model.RequestDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (ViewContext.HttpContext.User.IsInRole("Tenant"))
        {
        <div class="form-group">
            @Html.LabelFor(model => model.Appliances, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("selectAppliances", (MultiSelectList)ViewBag.ApplianceList, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
            <br />
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RentalManagement/Views/MaintenanceRequests/Delete.cshtml
@model RentalManagement.Models.MaintenanceRequest

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MaintenanceRequest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompletedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompletedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FixDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FixDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoursSpent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoursSpent)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RentalManagement/Views/MaintenanceRequests/Details.cshtml
@model RentalManagement.Models.MaintenanceRequest

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MaintenanceRequest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompletedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompletedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FixDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FixDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoursSpent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoursSpent)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RentalManagement/Views/MaintenanceRequests/Edit.cshtml
@model RentalManagement.Models.MaintenanceRequest

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Maintenance Request </h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MaintenanceRequest</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompletedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompletedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompletedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StatusDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StatusDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FixDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FixDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FixDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoursSpent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoursSpent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoursSpent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-1">
                <input type="submit" value="Save" name="saveBtn" class="btn btn-success" id="savebtn" />
            </div>
            <div class="col-md-1">
                <input type="submit" value="Close" name="closeBtn" class="btn btn-danger" id="closebtn"/>
            </div>
        </div>
    </div>
}
    <div class="container">
        <h3>
            <span class="label label-success" id="savedReq">@TempData["SavedChangesMessage"]</span>
        </h3>
        <h3>
            <span class="label label-danger" id="closeReq">@TempData["CloseRequestMsgAlert"]</span>
        </h3>
    </div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="~/Scripts/requestScript.js" type="text/javascript"></script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

RentalManagement/Views/MaintenanceRequests/Index.cshtml
@model IEnumerable<RentalManagement.Models.MaintenanceRequest>

@{
    ViewBag.Title = "Index";
}

<br />
<button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Create", "MaintenanceRequests")'">Create New Request</button>

@if (ViewContext.HttpContext.User.IsInRole("Admin")
    || ViewContext.HttpContext.User.IsInRole("Manager")
    || ViewContext.HttpContext.User.IsInRole("Staff"))
{
<br />
<h2> Requests per Asset</h2>
<table class="table">
    <tr>
        <th>
            Asset Name
        </th>
        <th>
            Number of requests
        </th>
    </tr>
    @foreach (var asset in (Dictionary<string, string>)ViewBag.NumRequestPerAsset)
    {
        <tr>
            <td>
                @Html.Raw(asset.Key)
            </td>
            <td>
                @Html.Raw(asset.Value)
            </td>
        </tr>
    }
</table>
}

<br />
<h2>Active Requests</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompletedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RequestDetail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StatusDetail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FixDetail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoursSpent)
        </th>
        <th>
            Options
        </th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.CompletedDate == null)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompletedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestDetail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatusDetail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FixDetail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoursSpent)
                </td>
                <td>
                    @if (ViewContext.HttpContext.User.IsInRole("Admin")
                        || ViewContext.HttpContext.User.IsInRole("Manager")
                        || ViewContext.HttpContext.User.IsInRole("Staff"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    }

                    @Html.ActionLink("Details", "Details", new { id = item.ID })

                </td>
            </tr>
        }
    }

</table>

<br />
<h2>Closed Requests</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompletedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RequestDetail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StatusDetail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FixDetail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoursSpent)
        </th>
        <th>
            Options
        </th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.CompletedDate != null)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompletedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestDetail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatusDetail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FixDetail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoursSpent)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                </td>
            </tr>
        }
    }

</table>
<script src="~/Scripts/requestScript.js" type="text/javascript"></script>